### ISSUE TITLE
Question: Server closing connection abruptly

### ISSUE THREAD

**Issue by flagoworld** [prom3theu5/iNGEN-Ark-RCON-Desktop#1]
I am creating something similar to this in another language and I used your code as a reference for how to communicate with servers. I have constructed my packets identically, but any time i write to the socket the server closes the connection with no response.

Is there something I'm missing here? Maybe you experienced the same thing somewhere along the way?

**Comment by flagoworld** [comment]
Bump, stop being a bum and answer my question. I know you've seen it. ;)

Don't worry, I'm not competing with you. I'm just creating this for other platforms because it's awesome. And it will be open source.

**Comment by prom3theu5** [comment]
Sorry I have been meaning to reply. Have been busy catching up with my day job projects since I took a holiday and returned.

Are you able to successfully authenticate or is the connection closing before this occurs?

Are you sure your're running the tcpclient in a separate long running thread?

It's not something I saw specifically while developing. What language are you writing it in?

**Comment by flagoworld** [comment]
Connection closed by remote peer on the first write to socket. Using objective c with cocoaasyncsocket, which should keep my socket open as long as the object instance is alive or until something else closes it.

Same server tested eith your client works.

**Comment by prom3theu5** [comment]
Hmm That is very strange.
There is an open issue on CocoaAsync's repo saying new connections immediately close. I have no idea if its related as I have never used that particular library myself:
https://github.com/robbiehanson/CocoaAsyncSocket/issues/323

**Comment by flagoworld** [comment]
Probably not the same since im creating a socket and not a server. But ill keep fiddling with it.

**Comment by prom3theu5** [comment]
Only other thing I can suggest is try making all your socket references strong, and remove any __weak declarations. 

From what I understand, iOS attempts to dispose of any weak sockets as soon as it possibly can.

My Apple-fu is very "pear shared" though :P
You could always use mono. There is a Sockets.Net portable class library which is compilable

Good Luck!
