### ISSUE TITLE
App freeze Win10

### ISSUE THREAD

**Issue by ghost** [prom3theu5/iNGEN-Ark-RCON-Desktop#2]
Hey, I love your tool. But recently I discovered that the App freezes on Win10 Pro 64bit after running for a few hours. I tried to find some logs but can't find any.

**Comment by prom3theu5** [comment]
Thanks for the feedback :)

I will add global Dispatcher Unhandled Exception logging tonight in an update.
It will allow a log file to be created at the time it crashes which we can look at to see where this is occurring (Hopefully :))

**Comment by prom3theu5** [comment]
I've pushed the update - Let's get to the bottom of this.

**Comment by ghost** [comment]
Thanks for the quick response. I just updated the tool and hope I can provide a log ASAP. Since it only happened after hours of running in the background I can't promise any results today :D

**Comment by prom3theu5** [comment]
Cheers. I know where the crash is now. A fix will be live in the morning

**Comment by prom3theu5** [comment]
New version Pushed. Hopefully will sort the issue. Admins will now need to grab their Steam API Key, and enter it in settings. There is a button to take you to the page next to the box for the key.

**Comment by ghost** [comment]
Awesome, thanks. I close the issue and maybe reopen if something happens. Had 0 freezes until now, so I think we are fine.

Keep up the great work!
