### ISSUE TITLE
Feature Request: Chat names in log files

### ISSUE THREAD

**Issue by DrunkMunki** [prom3theu5/iNGEN-Ark-RCON-Desktop#4]
Hello,
your original application saved chat logs with the players names in the chat.

> (10:38 PM) REEGZ (REEGZ): game stuff, not real life stuff
> (10:38 PM) Viles (Viles): yeah i dont care
> (10:38 PM) Nogaxeh (Nogaxeh): lol

But the newer version i am not getting the names, see below:

> (02:49 AM)  nah all good, catch ya bro
> (02:50 AM)  welp, I'm hopping off for the night, I'll probably be on tomorrow
> (02:50 AM)  see ya man
> (02:50 AM)  see ya bro

the main reason for this i log the chat so i can keep track of any abuse that may occur.
any chance we can get this put in, or am i missing a setting somewhere?

**Comment by prom3theu5** [comment]
Thanks for pointing this out.
I'll have it fixed and up tomorrow :)

**Comment by DrunkMunki** [comment]
any update on this?

**Comment by prom3theu5** [comment]
Just added two updates. The last update should fix this :)

**Comment by DrunkMunki** [comment]
issue fixed, thanks i can see the names in the chat logs
